### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#172]
It would be nice to have a Spanish translation of the app.

The _Translation Editor_ in _Android Studio_ let's you easily identify the missing translations as shown in the screenshot.

![Android-Studio-Translation-Editor](https://user-images.githubusercontent.com/144518/65724092-fe307d00-e0af-11e9-8dd6-743d6d00237b.png)

- [ ] Add new translations in `app/src/main/res/values-es` (ignore `placeholder` strings)
  - Adding a new language can be done via the _Translation Editor_: the earth icon at top left
- [ ] Optional: Add new translations in `app/src/ccc35c3/res/values-es` (becomes visible when you change the _Build Variant_)
- [ ] Optional: Add new translations in `app/src/cccamp2019/res/values-es` (becomes visible when you change the _Build Variant_)

# Related
- [Localize the UI with Translations Editor](https://developer.android.com/studio/write/translations-editor.html)

**Comment by vherasme** [comment]
Hello @johnjohndoe, Can I help with that? My first language is Spanish

**Comment by johnjohndoe** [comment]
@vherasme You are very welcome.

**Comment by vherasme** [comment]
Hi. I don't know why I would need to fork the repo instead of cloning it and creating another branch:

> Fork the repository into your personal GitHub account to start working.

**Comment by johnjohndoe** [comment]
@vherasme 

> ... fork the repo instead of cloning ...

GitHub uses "Fork" as a synonym for "Clone" - see the `Fork` button in the top right corner of a repository page.

> I have started by the way.

Nice. Please make sure to rebase your branch onto the latest commit of my `master` branch - I have added a few string lately.

**Comment by jMavarez** [comment]
I'm willing to help if it's still needed!

**Comment by johnjohndoe** [comment]
@jMavarez Your help is appreciated. It would be nice if you can review the translation once @vherasme pushes his branch.

**Comment by vherasme** [comment]
@johnjohndoe I am having problems with this:
```

org.xml.sax.SAXParseException; lineNumber: 17; columnNumber: 109; El prefijo "xliff" para el elemento "xliff:g" no está enlazado.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:284)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next
```

By the way I found your post in SO:
https://stackoverflow.com/questions/6158157/what-does-this-mean-xmlnsxliff-xml

**Comment by johnjohndoe** [comment]
@vherasme You are missing the namespace definition at the beginning of the XML document in `app/src/main/res/values-es/strings.xml`.

Change this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
```

to this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
```

The post is not from me - I just edited it :)

**Comment by rferromoreno** [comment]
Please if you still need help let me know. I'm also willing to contribute.

**Comment by johnjohndoe** [comment]
Please mind that I will **not** be able to reply quickly since I am on vacation for a while (Oct 3-31).

**Comment by vherasme** [comment]
I ran the app on my device last Sunday. I will do it again tonight to make sure everything works

**Comment by johnjohndoe** [comment]
Left to translate: the `cccamp2019` strings.

**Comment by vherasme** [comment]
@johnjohndoe Which ones? Pls give me instructions so I can keep working on it

**Comment by johnjohndoe** [comment]
@vherasme Please see the open checkbox in the issue description above.

**Comment by 0x5ubt13** [comment]
Hi, should this still be open I´d like to cooperate. I live in the UK but my first language is Spanish

**Comment by johnjohndoe** [comment]
@0x5ubt13 Yes, this issue is still open. I updated the description lately. One part is to add new and missing strings but it would also be helpful to review existing translations.

**Comment by luisAzcuaga** [comment]
I'm helping with this! 😁
