### ISSUE TITLE
NoSuchElementException: List is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#238]
Crash report from multiple users:

- Sent: 29.12.2019 - 05.01.2020
- App versions: [v.1.41.3](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.3), [v.1.41.4](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.4)
- Android versions: 9, 10
- Device models: MI 6, ELE-L29, Pixel 2

# Stacktrace
``` java
java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196)
at kotlin.collections.CollectionsKt.first(Unknown Source:0)
at info.metadude.android.eventfahrplan.database.repositories.LecturesDatabaseRepository.queryLectureByLectureId(LecturesDatabaseRepository.kt:36)
at nerd.tuxmobil.fahrplan.congress.repositories.AppRepository.readLectureByLectureId(AppRepository.kt:284)
at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.eventIdToLecture(EventDetailFragment.java:351)
at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.onViewCreated(EventDetailFragment.java:165)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
at android.app.Activity.performStart(Activity.java:7479)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

# Log
``` java
1 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"1534416922c64ff18491c2750cecaac66a6d65f5748be3893b532306994002d6", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 606; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 16:20)
2 D: viewDay(false)
3 D: meta.getNumDays() = 4
4 D: MyApp.task_running = NONE
5 D: lectureId = null
6 D: MyApp.lectureList contains 157 items.
7 D: onResume
8 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"1534416922c64ff18491c2750cecaac66a6d65f5748be3893b532306994002d6", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 606; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 16:20)
9 D: viewDay(false)
10 D: meta.getNumDays() = 4
11 D: MyApp.task_running = NONE
12 D: lectureId = null
13 D: MyApp.lectureList contains 157 items.
14 D: onResume
15 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"1534416922c64ff18491c2750cecaac66a6d65f5748be3893b532306994002d6", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 606; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 16:20)
16 D: viewDay(false)
17 D: meta.getNumDays() = 4
18 D: MyApp.task_running = NONE
19 D: lectureId = null
20 D: MyApp.lectureList contains 157 items.
21 D: onResume
22 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"1534416922c64ff18491c2750cecaac66a6d65f5748be3893b532306994002d6", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 606; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 16:20)
23 D: viewDay(false)
24 D: meta.getNumDays() = 4
25 D: MyApp.task_running = NONE
26 D: lectureId = null
27 D: MyApp.lectureList contains 157 items.
28 D: onResume
29 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"1534416922c64ff18491c2750cecaac66a6d65f5748be3893b532306994002d6", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 606; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 16:20)
30 D: viewDay(false)
31 D: meta.getNumDays() = 4
32 D: MyApp.task_running = NONE
33 D: lectureId = null
34 D: MyApp.lectureList contains 157 items.
35 D: onResume
36 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"1534416922c64ff18491c2750cecaac66a6d65f5748be3893b532306994002d6", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 606; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 16:20)
37 D: viewDay(false)
38 D: meta.getNumDays() = 4
39 D: MyApp.task_running = NONE
40 D: lectureId = null
41 D: MyApp.lectureList contains 157 items.
```

# User report
> Click on a shift

# Related
- [Issue #214: Don't use MyApp.lectureList to populate EventDetailFragment](https://github.com/EventFahrplan/EventFahrplan/pull/214)

**Comment by johnjohndoe** [comment]
@cketti For you interest: seem like the underlying bug is still around. I added some logging for future analysis.

**Comment by cketti** [comment]
PR #214 was never meant to fix the issue that the app crashes when an event couldn't be found in the database at all.

Updating the UI when the database has been updated should reduce the likelihood of this issue occurring. But there's always going to be a chance that the user selects an event that existed in the past and will have been removed by the time the detail view is shown. Code needs to be written to handle this case.
A similar case that needs to be handled: detail view of an event is opened, app is moved to the background, app syncs and event is removed, app is brought to the foreground. You'll have to figure out what the user experience should be in that case.

**Comment by johnjohndoe** [comment]
This error will be continued in #243 with more detailed error logging implemented as of v.1.41.5.
