### ISSUE TITLE
Lectures table does not contain a lecture with ID ... List is empty.

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#243]
:warning: This is the same error as #238. To get more detailed error logging has been added in version 1.41.5, see #239.

---

Crash report from a user:

- Sent: 10.01.2029
- App version: 1.41.5
- Android version: 8.1.0
- Device model: Aquaris X

# Stacktrace
``` java
java.lang.RuntimeException: Unable to start activity 
    ComponentInfo{info.metadude.android.congress.schedule/
    nerd.tuxmobil.fahrplan.congress.details.EventDetail}: 
    java.util.NoSuchElementException: List is empty.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2795)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2873)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6543)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by: java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:196)
at kotlin.collections.CollectionsKt.first(Unknown Source:0)
at info.metadude.android.eventfahrplan.database.repositories.LecturesDatabaseRepository.queryLectureByLectureId(LecturesDatabaseRepository.kt:38)
at nerd.tuxmobil.fahrplan.congress.repositories.AppRepository.readLectureByLectureId(AppRepository.kt:283)
at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.eventIdToLecture(EventDetailFragment.java:357)
at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.onViewCreated(EventDetailFragment.java:165)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
at android.app.Activity.performStart(Activity.java:7043)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
... 9 more
```

# Log
``` java
1 E: Lectures table does not contain a lecture with ID 5146. List is empty.
2 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag=W/"c597f7977a362860a09e1a1a19e1fa6556432546f71fbf3abc9ea6e99eed9c30", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 707; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2019-12-30 22:10)
3 D: viewDay(false)
4 D: meta.getNumDays() = 4
5 D: MyApp.task_running = NONE
6 D: lectureId = null
7 D: MyApp.lectureList = null
8 D: onResume
9 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

# User report
> Ich hatte gerade die app aktualisiert via fdroid.
> Dann gestartet.
> Overlay, das es Fahrplan Aktualisierungen gab per "später" weggeklickt.
> Angezeigt wurde mir Tag 2 mit einer meiner Engelschichten.
> Auf die Schicht geklickt, das gab den Fehler.

# Related
- [Issue #238: NoSuchElementException: List is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first](https://github.com/EventFahrplan/EventFahrplan/issues/238)
- [Issue #239: Record debug information about zombie lecture which sometimes crashes the app.](https://github.com/EventFahrplan/EventFahrplan/pull/239)

**Comment by johnjohndoe** [comment]
The update mechanism for _Engelsystem_ shifts can be found in `AppRepository#updateShifts`. There might be a smarter way to handle these updates.

Additionally, it might make sense to refresh the grid schedule screen once more via `MainActivity#fetchFahrplan`.

Please mind [this comment](https://github.com/EventFahrplan/EventFahrplan/issues/238#issuecomment-571130720) from @cketti when working on this issue.
