### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void RecyclerView$Adapter.notifyDataSetChanged()' on a null object reference

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#402]
Crash report from multiple users:

- Sent: 27.05.2020, 27.12.2020, 18.02.2021, 17.09.2021
- App version: 1.43.1, 1.47.0, 1.48.0-rC3-Edition, 1.52.0-LibreOffice-Edition, 1.52.1-DebConf-Edition
- Android version: 7.1.1, 7.1.2, 10, 11
- Device model: Pixel 2, Nexus 9, SM-M515F, GT-I9195, M2101K7AI

# Stacktrace
``` java
java.lang.RuntimeException: Unable to resume activity {info.metadude.android.congress.schedule/
  nerd.tuxmobil.fahrplan.congress.schedule.MainActivity}: java.lang.NullPointerException: 
  Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView
  $Adapter.notifyDataSetChanged()' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4657)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4690)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 
  'void androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged()' on a null object reference
at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanFragment.addRoomColumns(FahrplanFragment.java:335)
at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanFragment.viewDay(FahrplanFragment.java:298)
at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanFragment.onResume(FahrplanFragment.java:245)
at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2589)
at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:204)
at android.app.Activity.performResume(Activity.java:8136)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4647)
... 11 more
```

# Log
``` java
 0 D: Writing unhandled exception to: /data/user/0/info.metadude.android.congress.schedule/files/1.47.0-1613670366194.tracedroid
 1 D: viewDay(false)
 2 D: meta.getNumDays() = 4
 3 D: MyApp.task_running = NONE
 4 D: sessionId = null
 5 D: onResume
 6 D: MyApp.meta = Meta(eTag=W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b", numDays=4, subtitle=, timeZoneId=null, title=36th Chaos Communication Congress, version=mkdir; lounges 707; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2020-01-18 18:10)
 7 D: viewDay(true)
 8 D: fetch was pending, restart
 9 D: MyApp.task_running = FETCH
10 D: sessionId = null
11 D: onResume
12 D: Fetching schedule in onCreate bc. numDays==0
13 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

# User report
- nothing yet

# Related
- nothing yet

**Comment by krishnapriyar** [comment]
I've been looking into this but so far have been unable to reproduce it. If there are any certain steps to reproduce, that'll be good to know

**Comment by johnjohndoe** [comment]
Same here. I hope the extended logging brings new insides.
