### ISSUE TITLE
DeadSystemException in ConnectivityManager.getActiveNetworkInfo

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#49]
Crash report from a user:

- sent: 28.12.2017
- 1.33.1
- Android Version: 7.1.2
- Phone Model: GT-I9195

# Stacktrace
``` java
java.lang.RuntimeException: android.os.DeadSystemException
at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:772)
at nerd.tuxmobil.fahrplan.congress.autoupdate.UpdateService.onHandleIntent(UpdateService.java:154)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: android.os.DeadSystemException
... 6 more
```
# Log
``` java
0 D: Writing unhandled exception to: /data/user/0/info.metadude.android.congress.schedule/
    files/1.33.1-1514438261282.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$UncaughtHandler
```

**Comment by johnjohndoe** [comment]
Issue can't be reproduced. Added logging to be captured in crash report, see abbc59ee433730d2876b005fdf8657d4dc838678. Closing issue.
