### ISSUE TITLE
IllegalArgumentException:  Too small number of days: 6, date info list contains 10 items

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#529]
Crash via Google Play:

- Sent: 26.12.2022
- App version: [v.1.56.1](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.56.1)
- Branch: `master`

# Stacktrace
``` java
FATAL EXCEPTION: DefaultDispatcher-worker-   3
Process: info.metadude.android.rc3.schedule, PID: 5676
java.lang.IllegalArgumentException: Too small number of days: 6, date info list contains 10 items
    at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries(NavigationMenuEntriesGenerator.kt:51)
    at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries$default(NavigationMenuEntriesGenerator.kt:39)
    at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.toFahrplanParameter(FahrplanViewModel.kt:112)
    at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.access$toFahrplanParameter(FahrplanViewModel.kt:26)
    at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$updateUncanceledSessions$1$1.emit(FahrplanViewModel.kt:77)
    at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$updateUncanceledSessions$1$1.emit(FahrplanViewModel.kt:67)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
...
```

# Context
- Happens because the backend added further event days in front of the former "first" day.
- Handling needs to be discussed.

**Comment by MyIgel** [comment]
Just wanted to report that too as it happens during dev tests ^^

What would be a good workaround here?

**Comment by johnjohndoe** [comment]
Thanks for the update. Yes, sadly the current workaround is to reset the app (cache, data) and reinitialize the schedule and optionally shifts.

I am not able to work on a fix these days.

**Comment by MyIgel** [comment]
Workaround as in: don't load the engelsystem json again because if you do it crashes again (at least with my old config)

**Comment by johnjohndoe** [comment]
> the moment an erronous engelsystem shifts url can only be removed by deleting the whole app config ...

What is an erronous Engelsystem shift url for you? Can you not just replace that url with another "good" one?
Are you sure the url is the reason for the crash? Up to now I observed that the changed schedule triggers the crash.

**Comment by MyIgel** [comment]
Well i entered an URL to my test system and it crashed immediately after the save and subsequentially on every app start

**Comment by MyIgel** [comment]
Sadly i deleted the shifts during debugging before exporting the broken json :(

(but i think it was "2h shifts from yester day or the day before or something until event end" and another one with "shifts from event start (or before the event?) to end event.

**Comment by johnjohndoe** [comment]
You can send me you shifts URL in private (via mail) if you want me to take a look.
