### ISSUE TITLE
App crashes on 24/7 event

### ISSUE THREAD

**Issue by clonejo** [EventFahrplan/EventFahrplan#546]
I am currently trying to generate a frab/pentabarf schedule xml for Summer Games Done Quick: https://gamesdonequick.com/schedule/43 (i am not affiliated with GDQ)

Notably this event has _no break through the night_, it runs for 7 days with only short breaks.

# Environment
- App version: 1.56.1-JEV-Edition
- Android version: 13
- Branch:
- Device: Pixel 6

# How to reproduce
1. load either schedule URL as an alternate schedule XML:
   - https://clonejo.de/gdq/gdq-midnight.xml (days split after midnight US Central Time)
   - https://clonejo.de/gdq/gdq-recap.xml (days split after Daily Recap event, i prefer this variant)
2. confirm and and leave settings menu

# Observed behavior
- the app crashes:
```
java.lang.IllegalArgumentException: Too small number of days: 8, date info list contains 14 items
  at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries(NavigationMenuEntriesGenerator.kt:51)
  at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries$default(NavigationMenuEntriesGenerator.kt:39)
  at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.toFahrplanParameter(FahrplanViewModel.kt:112)
  at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.access$toFahrplanParameter(FahrplanViewModel.kt:26)
  at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$updateUncanceledSessions$1$1.emit(FahrplanViewModel.kt:77)
  at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$updateUncanceledSessions$1$1.emit(FahrplanViewModel.kt:67)
  at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
  at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
  at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
  Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@87b7ff1, Dispatchers.IO]
```

# Expected behavior
All events should be listed. [Giggity](https://github.com/Wilm0r/giggity) does accept these schedule XMLs, although it does shuffle the events to other days. It seems to add events to the previous day, until a cut off at 05:00. Since the apps are displaying the schedule separated by days, it would make sense that the XML is followed. Could also be a user choice, or a choice in the customization settings, i guess.

# Related
- #70 might be related, but the settings seems to have no impact on the crashing
- https://github.com/EventFahrplan/EventFahrplan/blob/8adfff670eeeae240d7285e6c3d4023d9d8e63a9/app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt#LL44C42-L44C43

**Comment by johnjohndoe** [comment]
Hi @clonejo, nice to read that you want to use this app for your event. Thank you for taking the time to prepare this report very descriptive.

I will ask a few question which might help to clarify the issue:

1. Did you follow the [customization guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/docs/CUSTOMIZING.md) to prepare your own app instance (specifically the product flavor part)?
2. Did you find the [schedule validation tool](https://c3voc.de/schedulexml/) to check the XML?
3. Did you do a fresh install (or clear cache and storage) of the app to load the schedule for the first time? This won't work with a published app such as JEV. The crash only happens if the number of days changes after the schedule has been loaded before, afaik.

Also, some additional words about the project:

4. The app is not designed and it does not aim to be a multi-event app such as Giggity.
5. The alternative schedule URL feature is intended for a backup URL if the main server URL is no longer reachable during the event. Internals in the app are not prepared to switch to a totally different event.
6. I do not recommend using a published app such as JEV for your event.
7. I never tried what happens when a schedule with no breaks is added. You can try that and find out but maybe its better to split it.

**Comment by clonejo** [comment]
Huh, i had not found the validator on my searches. Neither any documentation on the format. For Giggity, i resorted to reading their source code.

To be honest i don't intend to publish an app at all, so i am moving outside your intended use case here. I was just checking what apps i could get working.

Mostly i wanted to document that EventFahrplan may have an issue with 24/7 / marathon style events.

**Comment by johnjohndoe** [comment]
Thanks for sharing your finding nevertheless. For now, I will track it as a duplicate of issue #529.

If you intend to customize and deploy the app at some point feel free to reach out when you get stuck.

If that's fine for you - you can close the issue here.

**Comment by clonejo** [comment]
Thank you for your time!
