### ISSUE TITLE
37C3 Fahrplan App crashes when Engelsystem-JSON-URL is entered

### ISSUE THREAD

**Issue by mprt** [EventFahrplan/EventFahrplan#590]
# Environment
- App version: 1.62.0
- Android version: Android 10, LineageOS API-Level: llama (9), /e/ OS-Version 1.8.1-q-20230206257879-dev-enchilada
- Branch: 
- Device: OnePlus 6 (A6003)

# How to reproduce
1. Install App from F-Droid
2. enter URL: https://engel.events.ccc.de/shifts-json-export?key=.....

# Observed behavior
- App crashes immediately
- When i try to open it, it crashes immediately
- Upon opening, for a split second, I see something like an error message and two buttons ("Nein", "Fehlerbericht in email öffnen"), but the android "error message" immediately takes over.
- tried it twice (uninstalled and re-installed), same behaviour, I can share my key with a developer if needed.

# Expected behavior
- The Program should not crash,

![photo_5213261510846042464_y](https://github.com/EventFahrplan/EventFahrplan/assets/2391915/e4742fd9-9efa-426e-a5be-8ecd05d43caf)

**Comment by mprt** [comment]
If I enter an invalid URL (change/remove last digit of the key) there is a proper error message and the app works as intended.

**Comment by johnjohndoe** [comment]
I could not reproduce the crash on my device. Can we meet to analyze the problem? DECT 7872.

**Comment by mprt** [comment]
sure thing!
Your number did not work (yet).
I'm idle today from 10-11, then doing angel shifts at uptime (11h-13h) and zerotime bar (13-15h).
DECT 4024

**Comment by wlhlm** [comment]
I'm hitting the same issue. LineageOS 20. Feel free to hit me up DECT 2397, but won't be at the venue until after noon. Here is what I can see in my logs:

```
12-27 09:32:03.878 D/TraceDroid(16727): java.lang.IllegalArgumentException: Too small number of days: 4, date info list contains 5 items
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries(NavigationMenuEntriesGenerator.kt:51)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries$default(NavigationMenuEntriesGenerator.kt:39)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.createFahrplanParameter(FahrplanViewModel.kt:147)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.access$createFahrplanParameter(FahrplanViewModel.kt:34)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$fahrplanParameter$2.invokeSuspend(FahrplanViewModel.kt:58)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$fahrplanParameter$2.invoke(FahrplanViewModel.kt:0)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$fahrplanParameter$2.invoke(FahrplanViewModel.kt:0)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:33)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:0)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:0)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:76)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:590)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2896)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:638)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:458)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:36)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:304)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.channels.BufferedChannel.send(BufferedChannel.kt:0)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2$1$1.emit(Combine.kt:32)
12-27 09:32:03.878 D/TraceDroid(16727): 	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$special$$inlined$filter$1$2.emit(Emitters.kt:223)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:0)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-27 09:32:03.878 D/TraceDroid(16727): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-27 09:32:03.878 D/TraceDroid(16727): 	at android.os.Handler.handleCallback(Handler.java:942)
12-27 09:32:03.878 D/TraceDroid(16727): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-27 09:32:03.878 D/TraceDroid(16727): 	at android.os.Looper.loopOnce(Looper.java:201)
12-27 09:32:03.878 D/TraceDroid(16727): 	at android.os.Looper.loop(Looper.java:288)
12-27 09:32:03.878 D/TraceDroid(16727): 	at android.app.ActivityThread.main(ActivityThread.java:7924)
12-27 09:32:03.878 D/TraceDroid(16727): 	at java.lang.reflect.Method.invoke(Native Method)
12-27 09:32:03.878 D/TraceDroid(16727): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-27 09:32:03.878 D/TraceDroid(16727): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by wlhlm** [comment]
Here is my Engelsystem JSON export:

[engelsystem-export.zip](https://github.com/EventFahrplan/EventFahrplan/files/13777132/engelsystem-export.zip)

**Comment by johnjohndoe** [comment]
Thank you. I will try to contact you later. I haven't found time to do so yet.

**Comment by padumms** [comment]
I can confirm the bug.
Android 13. 
There was no way to start the app again without an immediate crash. Had to reinstall.

**Comment by johnjohndoe** [comment]
Yes. I looked into it for two hours. I have to find more time. Sorry for the trouble.

**Comment by mprt** [comment]
> Yes. I looked into it for two hours. I have to find more time. Sorry for the trouble.

don't worry, it's a Luxusproblem anyway.
enjoy the Congress :-)

**Comment by johnjohndoe** [comment]
@wlhlm, @mprt, @padumms I fixed the crash. The latest release (v.1.63.0) on Google Play contains it. It would be great if you could load your Engelsystem shifts into the app to see if everything works fine now. The new version will soon also appear in the F-Droid store.
