### ISSUE TITLE
UpdateService causes IllegalArgumentException: unexpected url:

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#66]
Crash report from a user:

- sent: 23.06.2018
- 1.33.4 (Droidcon Berlin Edition)
- Android version: 6.0.1
- Device model: Redmi Note 3

# Stacktrace
``` java
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

Caused by: java.lang.IllegalArgumentException: unexpected url:
at okhttp3.Request$Builder.url(Request.java:143)
at nerd.tuxmobil.fahrplan.congress.net.FetchFahrplanTask.fetch(FetchFahrplan.java:133)
at nerd.tuxmobil.fahrplan.congress.net.FetchFahrplanTask.doInBackground(FetchFahrplan.java:93)
at nerd.tuxmobil.fahrplan.congress.net.FetchFahrplanTask.doInBackground(FetchFahrplan.java:58)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

# Log
``` java
0 D: Writing unhandled exception to: /data/user/0/info.metadude.android.droidconberlin.schedule/files/1.33.4-1529781803659.tracedroid
1 D: intent = Intent { cmp=info.metadude.android.droidconberlin.schedule/nerd.tuxmobil.fahrplan.congress.autoupdate.UpdateService }
2 D: current handler class=com.android.internal.os.RuntimeInit$UncaughtHandler
```

**Comment by johnjohndoe** [comment]
Resolved in https://github.com/johnjohndoe/CampFahrplan/commit/e8b84230eeebf3b66fb48d4c06109c6ea9a86212. Released in [v.1.33.5-Droidcon-Berlin-Edition](https://github.com/johnjohndoe/CampFahrplan/releases/tag/v.1.33.5-Droidcon-Berlin-Edition).
