### ISSUE TITLE
UnknownHostException: Unable to resolve host

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#67]
Crash report from a user:

- sent: 25.06.2018
- 1.33.5 (Droidcon Berlin Edition)
- Android version: 8.0.0
- Device model: H4113

# Stacktrace
``` java
java.net.UnknownHostException: Unable to resolve host "cfp.droidcon.de": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
at java.net.InetAddress.getAllByName(InetAddress.java:787)
at okhttp3.Dns$1.lookup(Dns.java:40)
at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
... 26 more
```

# Log
``` java
0 D: Writing unhandled exception to: /data/user/0/info.metadude.android.droidconberlin.schedule/files/1.33.5 (Droidcon-Berlin-Edition)-1529911834949.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

**Comment by johnjohndoe** [comment]
Fixed in https://github.com/johnjohndoe/CampFahrplan/commit/d57570751c97e2925fe09971d2fcd052a02ae240. Release in [v.1.33.6-Droidcon-Berlin-Edition](https://github.com/johnjohndoe/CampFahrplan/releases/tag/v.1.33.6-Droidcon-Berlin-Edition).
