### ISSUE TITLE
NullPointerException: Meta.getNumDays() in LecturesAdapter

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#68]
> Happened to me only once and as I got it from background after using other apps a lot.

Crash report from a user:

- sent: 26.06.2018
- 1.33.6 (Droidcon Berlin Edition)
- Android version: 8.0.0
- Device model: ONEPLUS A3003

# Stacktrace
``` java
java.lang.RuntimeException: Unable to resume activity {info.metadude.android.droidconberlin.schedule/nerd.tuxmobil.fahrplan.congress.favorites.StarredListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int nerd.tuxmobil.fahrplan.congress.models.Meta.getNumDays()' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3811)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3851)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3052)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6798)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int nerd.tuxmobil.fahrplan.congress.models.Meta.getNumDays()' on a null object reference
at nerd.tuxmobil.fahrplan.congress.base.LecturesAdapter.initMapper(LecturesAdapter.java:200)
at nerd.tuxmobil.fahrplan.congress.base.LecturesAdapter.<init>(LecturesAdapter.java:43)
at nerd.tuxmobil.fahrplan.congress.favorites.LectureArrayAdapter.<init>(LectureArrayAdapter.java:19)
at nerd.tuxmobil.fahrplan.congress.favorites.StarredListFragment.initStarredList(StarredListFragment.java:131)
at nerd.tuxmobil.fahrplan.congress.favorites.StarredListFragment.onResume(StarredListFragment.java:124)
at android.support.v4.app.Fragment.performResume(Fragment.java:2401)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3181)
at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:470)
at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:459)
at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
at android.app.Activity.performResume(Activity.java:7126)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3785)
... 10 more
```

# Log
``` java
0 D: Writing unhandled exception to: /data/user/0/info.metadude.android.droidconberlin.schedule/files/1.33.6 (Droidcon-Berlin-Edition)-1530002628526.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

**Comment by johnjohndoe** [comment]
Fixed in https://github.com/johnjohndoe/CampFahrplan/commit/244bcd6c8babc2fc3c069241013950fd117ff2fc. Release in [v.1.33.7-Droidcon-Berlin-Edition](https://github.com/johnjohndoe/CampFahrplan/releases/tag/v.1.33.7-Droidcon-Berlin-Edition).

**Comment by johnjohndoe** [comment]
Fixed in https://github.com/johnjohndoe/CampFahrplan/commit/d9b48611dfc2338ac91d978a9b7c7284e62a6e11. Release in [v.1.34.2-FrOSCon-Edition](https://github.com/johnjohndoe/CampFahrplan/releases/tag/v.1.34.2-FrOSCon-Edition).
