### ISSUE TITLE
EventDetailFragment: IllegalArgumentException: Parameter specified as non-null is null: parameter event

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#81]
Crash report from a user:

- sent: 22.09.2018
- Version: [1.36.1 (Datenspuren Edition)](https://github.com/johnjohndoe/CampFahrplan/releases/tag/v.1.36.1-Datenspuren-Edition)
- Android version: 8.1.0
- Device model: MI 8

# Stacktrace
``` java
java.lang.RuntimeException: Unable to start activity 
    ComponentInfo{info.metadude.android.datenspuren.schedule/
    nerd.tuxmobil.fahrplan.congress.details.EventDetail}: java.lang.IllegalArgumentException: 
    Parameter specified as non-null is null: method 
    kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter event
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2813)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2891)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1614)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6648)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)

Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: 
    method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter event
at nerd.tuxmobil.fahrplan.congress.utils.EventUrlComposer.<init>(Unknown Source:2)
at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.onViewCreated(EventDetailFragment.java:237)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
at android.app.Activity.performStart(Activity.java:7118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2776)
... 9 more
```

# Log
``` java
0 D: Writing unhandled exception to: /data/user/0/
     info.metadude.android.datenspuren.schedule/files/1.36.1 (Datenspuren Edition)-1537567710095.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

**Comment by johnjohndoe** [comment]
# How to reproduce, scenario 1
1. Load a schedule update which contains a **new** event entry.
2. The schedule changes dialog is shown. Tap the `Browse` button.
3. The changes list is shown. Tap the **new** event item.

# How to reproduce, scenario 2
1. Load a schedule update which contains a **new** event entry.
2. The schedule changes dialog is shown. Tap the `Later` button.
3. Select the overflow menu item `Schedule changes`.
4. The changes list is shown. Tap the **new** event item.

# Expected behavior
- The event detail screen opens.

# Observed behavior
- The app crashes. :boom:
